### ISSUE TITLE
Firestore: Collection SnapshotListener

### ISSUE THREAD

**Issue by SeriousM** [TobiasBuchholz/Plugin.Firebase#103]
Hi!

When I use `ICollectionReference.AddSnapshotListener<T>(onChange => {...})` the `onChange` contains two collections:

* DocumentChanges:
  * Contains a list of `DocumentChange` which consists of `ChangeType` and `DocumentSnapshot` of type `IDocumentSnapshot`.
  * The interface `IDocumentSnapshot` is empty - no reference to the actual document.
* Documents:
  * Contains the actual documents (plural!) of all the changes happened but without the ChangeType.
* `GetDocumentChanges()` which returns a list of `DocumentChange` as the `DocumentChanges` property above.
  * Why does this method exists?

How do I get the document to the document change like
* all added
* all removed
* all modified

Thanks!

**Comment by TobiasBuchholz** [comment]
Hi, the `DocumentChange` object did include indeed a reference to the `IDocumentSnapshot` interface which was rather useless. I've created a new version 1.2.5 of the plugin which references the `IDocumentSnapshot<T>` interface instead, so you can now use its `Data` property to access your data regarding to the change like this:
```c# 
onChanged.DocumentChanges.First().DocumentSnapshot.Data
```

The `GetDocumentChanges()` method returns an enumerable of the documents that changed since the last snapshot. You can pass `true` or `false` to it to include metadata-only changes, so I think that's why the method exists.

You can take a look at the official [firebase docs](https://firebase.google.com/docs/firestore/query-data/listen) for additional information. Furthermore I've incooperated this new code at the `gets_real_time_updates_on_multiple_documents()` test method of the `FirestoreFixture`, so you can take a look there as well. 

https://github.com/TobiasBuchholz/Plugin.Firebase/blob/97e254870ea7765eed20eaaac51c4fa3b44d79dd/tests/Plugin.Firebase.IntegrationTests/Firestore/FirestoreFixture.cs#L306

**Comment by SeriousM** [comment]
Hi Tobias, thank you again for your excellent support and all that information. I will check this new version tomorrow.
You're work is very appreciated!
