### ISSUE TITLE
Exception because of missing Activity on Android

### ISSUE THREAD

**Issue by rgiurea** [TobiasBuchholz/Plugin.Firebase#17]
Hi,

thanks for the grate library. For our use case it works grate. 

We noticed that on Android sometimes, normally on app resume or if you activate "Don't keep activities" in developer settings your library throws this exception:

"_**Current Activity is null, ensure that the MainApplication.cs file is setting the CurrentActivity in your source code so Firebase Analytics can use it.**_"

This are my questions :)

1. Can we ignore it by "try-catching" it and your library will "recover" itself. Does it fetch on every call the current activity? This would mean we lose maybe one event but after the activity is instantiated your library will continue to work correctly
2. Can we set the activity in any way?
3. Is it a bug that can be fixed or is it intended behaviour?

Thanks a lot for your answer!

Cheers.

**Comment by TobiasBuchholz** [comment]
Hi, thanks for the feedback! :)

The auth part of Plugin.Firebase is using James Montemagno's [Plugin.CurrentActivity](https://github.com/jamesmontemagno/CurrentActivityPlugin) to handle the current activity and this library gets initialized in the `FirebaseAuthImplementation.Initialize(Activity activity, Bundle savedInstanceState, string googleRequestIdToken)` method. 

The plugin tries to access the current activity by calling `CrossCurrentActivity.Current.Activity` when needed and if this call returns null the mentioned exception will be thrown. I guess you could try to catch the exception and call the Initialize-method again. I wouldn't consider it as a bug since normal users won't activate "Don't keep activities" in developer settings. 

Hope this helps, cheers

**Comment by rgiurea** [comment]
OK. At the moment I catch the exception, so no crash occurs anymore. This doe not happen only with the "Don't keep activity" option on. It happens also when you get your app from the background after "some time". I will keep an eye on it and see if I can localise a fix and put it here if I find one.
