### ISSUE TITLE
MAUI DotNet 7 simple sample please

### ISSUE THREAD

**Issue by ClausElmann** [TobiasBuchholz/Plugin.Firebase#204]
Could you please add a simple push notification sample app, It seem almost imposible for everybody to make i work, thanks in advance

**Comment by andyzukunft** [comment]
Hey Claus,

the Playground contains a Push example or am I mistaken?

Could you elaborate on what you require?

**Comment by ClausElmann** [comment]
> Hey Claus,
> 
> the Playground contains a Push example or am I mistaken?
> 
> Could you elaborate on what you require?

Hey Andy

The Playground sample is .net 6 not 7 - and even if i try that on android emulator, i get this error
Java.Lang.IllegalStateException: 'Default FirebaseApp is not initialized in this process com.tobishiba.playground. Make sure to call FirebaseApp.initializeApp(Context) first.'

**Comment by andyzukunft** [comment]
Hmm. I guess something broke when the package was redesigned. My application works just fine using .NET 7 and .NET 8 (basic tests, not used on iOS so far).

I will have a look - possibly create a dedicated demo application to simplify the implementation.

**Comment by ClausElmann** [comment]
> Hmm. I guess something broke when the package was redesigned. My application works just fine using .NET 7 and .NET 8 (basic tests, not used on iOS so far).
> 
> I will have a look - possibly create a dedicated demo application to simplify the implementation.

Thanks, that would be awesome, can't wait to try it out 👍

**Comment by andyzukunft** [comment]
I created a demo app using .NET 7. I specifically specify the latest (.NET 7 supported) Android and iOS version and limit on how old Android and iOS version are allowed to be. I just prefer to control the versions more closely.

Please test if this works for you. If it does I will talk to Tobias if he wants a dedicated MAUI project just for Cloud Messaging.

Pull Request: https://github.com/TobiasBuchholz/Plugin.Firebase/pull/212
You can get the code directly from here: https://github.com/andyzukunft/Plugin.Firebase

Note:
I also received the error `Default FirebaseApp is not initialized in this process`. This is because the google-service.json / Firebase Cloud Messaging is not properly configured. Please ensure you create you own Firebase project and use the correct google-service.json. I added the file to the gitignore so it won't get added by accident.
Also: App only tested with Android as iOS adds additional complexity for interfacing Google and Apple.

**Comment by ClausElmann** [comment]
Great, thanks a lot. I will give it a spin tomorrow. I did download my own
JSON file, but can't be sure if there is some issue with it. What was wrong
with yours?

søn. 15. okt. 2023 22.56 skrev Andy Zukunft ***@***.***>:

**Comment by andyzukunft** [comment]
The project name in Firebase has to match the `ApplicationId` in the `.csproj`. I commented the relevant parts (I think).

You can attach the debugger in `AppShell.xaml.cs` after you have checked and provided all the necessary elements.

**Comment by ClausElmann** [comment]
Hi @andyzukunft 

Great, it works now, I get the FCM Token.

I had to delete my Firebase project, and recreate it, so something must have been wrong there.

**Comment by andyzukunft** [comment]
Sounds great. Happy to help!
