### ISSUE TITLE
[Feature] Implement Apple Sign In authentication method

### ISSUE THREAD

**Issue by Kapusch** [TobiasBuchholz/Plugin.Firebase#23]
Hi @TobiasBuchholz ,

Again, thanks for this great library for which I will probably give a hand for new features.
I just wonder about if there is already a possibility to authenticate to Firebase using Apple Sign In ?

If no, any idea about how should we implement it ? With [Xamarin.Essentials](https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator?context=xamarin%2Fxamarin-forms&tabs=ios#apple-sign-in) maybe ?

Thanks in advance.

**Comment by Kapusch** [comment]
@TobiasBuchholz , I have provided an implementation for Apple Sign In via OAuth credential, it works fine.
You can check the solution in my forked repo : https://github.com/Kapusch/Plugin.Firebase/commit/edd947fa8e5fa31a4c35799ee5af00a686a400ad

If you're fine with that solution, then I'll provide an example in your Samples project.

Just tell me if you would rather prefer having the specific [Apple Sign In workflow from Xamarin.Essentials](https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator?context=xamarin%2Fxamarin-forms&tabs=ios#apple-sign-in) directly in your library, so that it'd be smoother for the developer to simply just call "SignInWithAppleAsync()" with no parameter, as you did for Google & Facebook authentication.

**Comment by TobiasBuchholz** [comment]
Hi @Kapusch, thank you very much for your feedback and interest in the library! 

Unfortunately it's quite hard for me to see the relevent changes in your implementation because of all the code formatting differences. 

On the `development` branch I've added an `.editorconfig` file that handles the code formatting and can be used to apply formatting rules by running `dotnet format src/Plugin.Firebase.sln` in the console. 

Please checkout that branch, apply your changes and code formatting and create a Pull Request, so I can merge it into the project if everything works well. For more information on how to contribute, take a look at the [README](https://github.com/TobiasBuchholz/Plugin.Firebase#contributions).

**Comment by Kapusch** [comment]
Sadly I am currently not much available, but I will keep you informed as soon as I can do it.

**Comment by Kapusch** [comment]
This will be covered with #37
