### ISSUE TITLE
MAUI Firebase iOS not building

### ISSUE THREAD

**Issue by RR99Link** [TobiasBuchholz/Plugin.Firebase#240]
I am trying to implement and compile with Visual Studio 2022 in Windows 11 with push notifications in my MAUI application for both Android and iOS. I receive the following error when building: "Unable to copy file "D:\p\xamarin.firebase.ios.installations\8.10.0.3\lib\net6.0-ios15.4\Firebase.Installations.resources\FirebaseInstallations.xcframework\ios-arm64_x86_64-simulator\FirebaseInstallations.framework\Headers\FIRInstallationsErrors.h" to "bin\Debug\net8.0-ios\iossimulator-x64\Firebase.Installations.resources\FirebaseInstallations.xcframework\ios-arm64_x86_64-simulator\FirebaseInstallations.framework\Headers\FIRInstallationsErrors.h". Could not find a part of the path 'bin\Debug\net8.0-ios\iossimulator-x64\Firebase.Installations.resources\FirebaseInstallations.xcframework\ios-arm64_x86_64-simulator\FirebaseInstallations.framework\Headers\FIRInstallationsErrors.h'"

I have already a custom Nuget configuration with a minimal path (D:\p), enabled long paths in the registry and in the 'Local Group Policy Editor'.

Tried to implement Plugin.Firebase --> path too long Tried to implement Plugin.Firebase.CloudMessaging and Plugin.Firebase.Core --> can't build without errors because the path is too long

**Comment by andyzukunft** [comment]
In my humble opinion: Your export path
`bin\Debug\net8.0-ios\iossimulator-x64\Firebase.Installations.resources\FirebaseInstallations.xcframework\ios-arm64_x86_64-simulator\FirebaseInstallations.framework\Headers\FIRInstallationsErrors.h` 
is exceeding the Windows file length of 260 letters. Somewhere there is a component which still has problems with this.

Can you please count your absolute ouput path letters?

**Comment by RR99Link** [comment]
I think the path length problem is with the Plugin.Firebase.Auth component of the Plugin.Firebase. 
I resolved It by installing directly Plugin.Firebase.Core and Plugin.Firebase.CloudMessaging, but the problem still remains for Plugin.Firebase

**Comment by AlleSchonWeg** [comment]
This worked for me: https://github.com/xamarin/GoogleApisForiOSComponents/issues/640#issuecomment-1854032707

**Comment by IeuanWalker** [comment]
Tried to reference all the related issue on here - https://github.com/xamarin/GoogleApisForiOSComponents/issues/639

To get Plugin.Firebase.CloudMessaging working, do the following -

1. Add nuget.config file to the root of your solution
> this changes the default nuget cache location for your project
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<config>
		<add key="globalPackagesFolder" value="c:\temp" />
	</config>
</configuration>
```
2. Change the default bin/ obj folder location. In your csproj add the following -
```xml
<BaseOutputPath>c:\bin</BaseOutputPath>
<BaseIntermediateOutputPath>c:\obj</BaseIntermediateOutputPath>
```

3. Restart VS
4. VS will still fail to run a nuget restore, but works fine running the command from powershell. Got too the root of your solution  and run `nuget restore`
5. You should be able to run a build/ run the app via VS now

**Comment by Grzesik** [comment]
Hi, I could manage the problem and now I can compile the iOS .Net 8 Maui App with Pulgin.Firtebase. I used "dotnet restore" to get the nuget package. But now I'd like to publish the app and I can't create an archive with the Archive Manager from Visual Studio 2022, because the path is too long! The zip file can be craeted, but the Unzip task crashes. The path, where the zip file is created is:
C:\Users\Marian.GRZESIK\AppData\Local\Xamarin\iOS\Archives\2024-01-05
When I try to unzip the file in c:\tmp, than it works.
Is it possible to shorten the paths? It worked well in Xamarin.Forms, but in .Net Maui it doesn't.

**Comment by faceoffers28** [comment]
Here's more information on the issue. 

https://github.com/dotnet/maui/issues/17828

I wonder if the app would Publish / Build using an Azure DevOps Pipeline???

**Comment by coop-tim** [comment]
After struggling with this myself for multiple days and slogging through misleading errors, fiddly/brittle config and red herring warnings, I thought it best to give back a working solution to the community.

This repo contains a fairly minimal working .NET 8 project targeting iOS and Android with Firebase Cloud Messaging, Analytics and the relevant build pipelines to get them built and pushed into App Center.

https://github.com/coop-tim/maui-sample

Hoping this helps whilst the root issues are worked on.

**Comment by AdamEssenmacher** [comment]
@TobiasBuchholz we should start consolidating these long path problems into one issue and close the rest as duplicates.

The answer is the same for all of them:

- The long path problem is caused by XCFramework format. These are just naturally going to have long file names.
- Visual Studio (Windows) is fundamentally not compatible with long file names.
- There's nothing _this_ plugin can do about it. Issues should be opened with the Visual Studio team and the iOS components team over at https://github.com/xamarin/GoogleApisForiOSComponents (for all the good it'll do you...)
- This doesn't affect macs, which don't have an issue with the long file names.
- The plugin is still buildable on VS (Windows) _as long as you run dotnet restore outside of the IDE_. However, the archiving will probably still need to happen on a mac.

**Comment by TobiasBuchholz** [comment]
@coop-tim thanks a lot for your sample project and it's extensive description! I've referenced it in the [sample section](https://github.com/TobiasBuchholz/Plugin.Firebase#documentation-and-samples) of the plugin's readme 👍

@AdamEssenmacher I've added a [troubleshooting section](https://github.com/TobiasBuchholz/Plugin.Firebase#troubleshooting) to the plugin's readme and copied some text from @coop-tim's project description that explains how to resolve the long path issue as well as your bullet points as additional hints.
