### ISSUE TITLE
Can't add Plugin.Firebase having NET7

### ISSUE THREAD

**Issue by dankorhn** [TobiasBuchholz/Plugin.Firebase#270]
When I try to add appear this error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not find a part of the path 'C:\Users\derh\nuget\packages\xamarin.firebase.ios.installations\8.10.0.3\lib\net6.0-ios15.4\Firebase.Installations.resources\FirebaseInstallations.xcframework\ios-arm64_x86_64-simulator\FirebaseInstallations.framework\Headers\FirebaseInstallations-umbrella.h'.		

Is no there available a versión for .net 7?

**Comment by logikonline** [comment]
This still errors with the parth shortened as others recommend

`MSB3030	Could not copy the file "c:\nuget\xamarin.firebase.ios.cloudfirestore\8.10.0.3\lib\net6.0-ios15.4\Firebase.CloudFirestore.resources\grpc.xcframework\ios-arm64\grpc.framework\PrivateHeaders\src\core\ext\upb-generated\envoy\config\filter\network\http_connection_manager\v2\http_connection_manager.upb.h" because it was not found.		
`

**Comment by AdamEssenmacher** [comment]
See: https://github.com/TobiasBuchholz/Plugin.Firebase?tab=readme-ov-file#windows-11-long-path-issue

**Comment by andyzukunft** [comment]
How is this helpful? It seems the iOS target framework is only activated if you are NOT using a Windows computer. I doubt a very lot of people have a special macOS setup (Visual Studio for Mac, ...) just for iOS compilation.
