### ISSUE TITLE
[Feature] Cover all data types that Cloud Firestore supports

### ISSUE THREAD

**Issue by Kapusch** [TobiasBuchholz/Plugin.Firebase#29]
I can see that some of the [data types that Cloud Firestore supports](https://firebase.google.com/docs/firestore/manage-data/data-types?hl=en) cannot be stored in the database.

For example, it is not possible to store a document which contains a reference to another document :
```csharp
public class SimpleItem
    {
        [FirestoreDocumentId]
        public string Id { get; set; }

        [FirestoreProperty(nameof(Title))]
        public string Title { get; set; }

        [FirestoreProperty(nameof(DocReferencePath))]
        public string DocReferencePath { get; set; }

        [FirestoreProperty(nameof(DocReference))]
        // This is not going to be stored in the database
        public IDocumentReference DocReference { get; set; }
    }
```

**Comment by Kapusch** [comment]
Hello @TobiasBuchholz , I have been able to cover the "reference" data type so that it can be stored in Firestore.
You can check implementation [here](https://github.com/Kapusch/Plugin.Firebase/commit/afb7a92e79681638a10afd86a0dbcd0fbace5ab2).

However, I don't know yet about how to cover the other missing data types. Any idea ?

**Comment by TobiasBuchholz** [comment]
Hi @Kapusch, thank you very much for your feedback and interest in the library! 

Unfortunately it's quite hard for me to see the relevent changes in your implementation because of all the code formatting differences. 

On the `development` branch I've added an `.editorconfig` file that handles the code formatting and can be used to apply formatting rules by running `dotnet format src/Plugin.Firebase.sln` in the console. 

Please checkout that branch, apply your changes and code formatting and create a Pull Request, so I can merge it into the project if everything works well. For more information on how to contribute, take a look at the [README](https://github.com/TobiasBuchholz/Plugin.Firebase#contributions).

**Comment by Kapusch** [comment]
Sadly I am currently not much available, but I will keep you informed as soon as I can do it.
