### ISSUE TITLE
Installing Plugin.Firebase.Crashlytics on my project causes building to hang

### ISSUE THREAD

**Issue by BioTurboNick** [TobiasBuchholz/Plugin.Firebase#313]
I'm on Windows 11 23H2, Visual Studio 17.10.3

I used the developer terminal to get around the long path issue to add the package Plugin.Firebase.Crashlytics to my MAUI app.

When trying to build, the build output shows it gets stuck after `Build started at xxxx...` but before building any particular project. The build can in theory be cancelled, but Visual Studio hangs soon after, e.g. trying to close

Might still be a subsequent effect of the long path issue. All I know is that the plugin just doesn't work.

**Comment by AdamEssenmacher** [comment]
Can you provide a repro project?

**Comment by BioTurboNick** [comment]
Not in short order. Already spent half a day on narrowing the cause to this package and would rather pursue options more likely to work.

**Comment by AdamEssenmacher** [comment]
> rather pursue options more likely to work.

If all you need is crash / error reporting for a MAUI app, Crashlytics really isn't the best OOTB solution. Something like Raygun is probably better since it's specifically designed for MAUI / .NET.

If it absolutely needs to be Crashlytics, or if you're using other Firebase tools, you'll need to build your own native SDK bindings. The binding libraries published by Microsoft are [out of date and deprecated](https://github.com/xamarin/GoogleApisForiOSComponents), so you'd most likely want to use [my fork](https://github.com/AdamEssenmacher/GoogleApisForiOSComponents) as a starting point. These are the bindings that you currently find to be insufficient, so if you can improve them at all contributions back would be appreciated.

Microsoft's latest guidance for this situation is build your own [slim bindings](https://github.com/Redth/DotNet.Platform.SlimBindings), which wouldn't carry all the extra overhead of having to deal with the temperamental XamarinBuildDownload and extra project setup.

Good luck!

**Comment by AdamEssenmacher** [comment]
I'm closing the issue. Feel free to reopen it with a repro project after reading through https://github.com/AdamEssenmacher/GoogleApisForiOSComponents/blob/main/Readme.md#important-installation-instructions-and-usage-notes
