### ISSUE TITLE
Cannot build release Android with 3.0.0 Plugin.Firebase.CloudMessaging

### ISSUE THREAD

**Issue by GorillaSpring** [TobiasBuchholz/Plugin.Firebase#346]
I am trying to update Plugin.Firebase.CloudMessaging to 3.0.0.  Currently using 2.0.4

I can build and debug (emulator) with 3.0.0, but cannot build release.  Visual Studio simply does not complete the build.  Have tried rebooting, deleting bin/obj, etc.  Noting works.

VS is 17.11.4  (updated today).  Build machine is Windows 11.

As a note, I am having all kinds of issues with VS and Mac build hosts.  This is being investigated by MS.  Don't think it is related.

Nugit packages are being restored correctly.  Package references are all fine.

Just building Release mode is the issue.

csproj   (change 3.0.0 to 2.0.4 and ALL is good).

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-android'">
    <PackageReference Include="Karamunting.Android.Natario1.Transcoder">
      <Version>0.9.1</Version>
    </PackageReference>
    <PackageReference Include="Plugin.Firebase.CloudMessaging" Version="3.0.0" />
    <GoogleServicesJson Include="google-services.json" />

	  <PackageReference Include="Xamarin.AndroidX.Core" Version="1.12.0.2" />
	  <PackageReference Include="Xamarin.AndroidX.Collection" Version="1.3.0.1" />
	  <PackageReference Include="Xamarin.AndroidX.Collection.Ktx" Version="1.3.0.1" />
	  <PackageReference Include="Xamarin.AndroidX.Activity.Ktx" Version="1.8.0.1" />
	  <PackageReference Include="Xamarin.AndroidX.Browser" Version="1.6.0.2" />
  </ItemGroup>

**Comment by AdamEssenmacher** [comment]
I don't think 2.0.4 -> 3.0.0 changed anything on the Android side.

**Comment by codychaplin** [comment]
Just to piggyback off this issue because I'm not sure what GorillaSpring's exact error was, I wasn't able to build in debug in Visual Studio due to many of these errors:
```
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5034,5): error MSB3030: Could not copy the file "C:\n\adame.firebase.ios.core\10.24.0.1\lib\net6.0-ios16.1\Firebase.Core.resources\FirebaseCoreInternal.xcframework\ios-arm64_x86_64-simulator\FirebaseCoreInternal.framework\Modules\FirebaseCoreInternal.swiftmodule\arm64-apple-ios-simulator.private.swiftinterface" because it was not found.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5034,5): error MSB3030: Could not copy the file "C:\n\adame.firebase.ios.core\10.24.0.1\lib\net6.0-ios16.1\Firebase.Core.resources\FirebaseCoreInternal.xcframework\ios-arm64_x86_64-simulator\FirebaseCoreInternal.framework\Modules\FirebaseCoreInternal.swiftmodule\x86_64-apple-ios-simulator.private.swiftinterface" because it was not found.
```
So I did so using the cli successfully, then after that I was able to build normally. I then did the same steps for release mode but it seems like I have to build each time via the cli which isn't too big a deal, but when I go to publish (archive) for Android, it fails because of the above issue.

If I'm building for Android, why are the iOS specific files included and therefore failing? I would rather avoid archiving via cli because those builds won't show up in the archive manager.

**Comment by GorillaSpring** [comment]
I have not had time to try anything to fix this.  It is possible this is just a Visual Studio / Maui thing.  I am going to try to set the build folders to be c:\bin and c:\obj (or something like that).  I will post an update if that fixes things.   I am not seeing the issues @codychaplin  is seeing.   I am using VS Pro.

**Comment by AdamEssenmacher** [comment]
https://github.com/AdamEssenmacher/GoogleApisForiOSComponents?tab=readme-ov-file#the-build-is-hanging ?

**Comment by codychaplin** [comment]
@AdamEssenmacher I am using the Plugin.Firebase libraries, so I'm not directly referencing your packages. Is there a way around that when using Plugin.Firebase? Also regarding the archiving, your docs mention `It will probably still choke during archiving though, so either do that step directly on a mac or try it on the CLI as well.`, so this means even for Windows/Android (after following all the steps for the long path issue), the only way to archive will be through the CLI and therefore I can't use the archive manager anymore?

**Comment by AdamEssenmacher** [comment]
> I am using the Plugin.Firebase libraries, so I'm not directly referencing your packages. Is there a way around that when using Plugin.Firebase?

If you're not directly referencing the AdamE.* packages in your .csproj, then you can ignore my comment.

Regarding my note about "archiving", I am referring to the XCode-specific step of generating an .xcarchive--not about the 'Archive Manager' Visual Studio tool necessarily. I mention this because, outside of Visual Studio, the concept of 'archiving' an Android app isn't really a thing. We'd just call it 'building for release' or something like that.

With that in mind...

> so this means even for Windows/Android (after following all the steps for the long path issue), the only way to archive will be through the CLI and therefore I can't use the archive manager anymore?

If 'publishing' an Android app through Visual Studio for release is failing due to iOS-related build steps, that would seem to indicate that Visual Studio is probably trying to build both apps, no? I would guess that is because of MAUI's single-project configuration. Try removing `net8.0-ios` from your `TargetFrameworks` and try publishing your Android app again.

**Comment by codychaplin** [comment]
Dammit, I didn't even think to remove the ios target framework... That seemed to fix it! Thanks again for the clarification!

**Comment by AdamEssenmacher** [comment]
That sounds annoying. Probably feedback for the MAUI and or Visual Studio teams... You can specify your target frameworks on CLI. I can't think of a good reason Visual Studio should be trying to build for anything other than the Android target when publishing and Android app.
