### ISSUE TITLE
NET9

### ISSUE THREAD

**Issue by awasilik** [TobiasBuchholz/Plugin.Firebase#373]
Hey,
do you have plans to update to NET9?

If so, when could it be expected (more or less)

**Comment by AdamEssenmacher** [comment]
Does the plugin not work with 9?

**Comment by jerry2007** [comment]
yes with .Net 9 it not works on iOS

**Comment by awasilik** [comment]
True, it's a defect in the bindings library. I issued it to the creator
https://github.com/AdamEssenmacher/GoogleApisForiOSComponents/issues/56

**Comment by robertmaxted** [comment]
It seems to be working fine for me with .NET 9 + Jetbrains Rider..?

**Comment by kevinderycke** [comment]
Yes not works on my side too.

**Comment by AdamEssenmacher** [comment]
https://github.com/xamarin/xamarin-macios/wiki/.NET-9-release-notes#type-registrar-managed-static-as-the-new-default ?

**Comment by AdamEssenmacher** [comment]
The plugin is known to work with .NET9, and the scope of this issue is starting to sprawl. We should update the project readme to include the registrar configuration step for .NET9.

@domneedham your issue doesn't really sound like a .net 9 problem on the surface, but you never know. If you're still having trouble, please open a separate issue with more details--preferably a minimum repro project demonstrating the problem. There are a handful of other issues (both open and closed) that sound like they could be similar.
