### ISSUE TITLE
[Android] Firestore: Couldn't put object of type Plugin.Firebase.Android.Firestore.DocumentReferenceWrapper into HashMap

### ISSUE THREAD

**Issue by Kapusch** [TobiasBuchholz/Plugin.Firebase#53]
Hi @TobiasBuchholz, I am currently testing your library on my Android app, and there's actually an error when setting data to a document reference using : `batch.SetData(shortUserReference, shortUserAccount);`

## StackTrace
```
System.ArgumentException: Couldn't put object of type Plugin.Firebase.Android.Firestore.DocumentReferenceWrapper into HashMap
  at System.Collections.Generic.DictionaryExtension.Put (Java.Util.IMap this, System.Object key, System.Object value) [0x00273] in <becdb5103fb14132a70e7e52fa7d7747>:0 
  at System.Collections.Generic.DictionaryExtension.ToHashMap (System.Object this) [0x00050] in <becdb5103fb14132a70e7e52fa7d7747>:0 
  at Plugin.Firebase.Android.Firestore.WriteBatchWrapper.SetData (Plugin.Firebase.Firestore.IDocumentReference document, System.Object data, Plugin.Firebase.Firestore.SetOptions options) [0x00032] in <becdb5103fb14132a70e7e52fa7d7747>:0 
```

## Setup
Visual Studio Community 2022 for Mac (17.0.7)
Xamarin.Android (12.3.3.3)
Xamarin.Forms (5.0.0.2012)
Plugin.Firebase V1.1.2

Here is an extract of the model I'm trying to store :
```
    public partial class ShortUser
    {
        [FirestoreProperty(nameof(Username))]
        public string Username { get; set; }

        [FirestoreProperty(nameof(UserId))]
        public IDocumentReference UserId { get; set; }

        [FirestoreProperty(nameof(ProfilePicture))]
        public Photo ProfilePicture { get; set; }
    }
```

## Context
I guess it's the IDocumentReference field that is causing the issue. But I've seen something similar which you already solved in the past : #7 
Could you please have a look ? Thanks in advance for your help 🙏

**Comment by Kapusch** [comment]
Hi @TobiasBuchholz , please find this MRE to reproduce the issue on Android : [PluginFirebase_Issue_55.zip](https://github.com/TobiasBuchholz/Plugin.Firebase/files/9366135/PluginFirebase_Issue_55.zip)
All you need to do is pressing the button specific for this issue

Thanks in advance !

**Comment by TobiasBuchholz** [comment]
Hmm, after running your test project both button clicks seemed to work, see the screenshots:

![Screenshot_20220818-153515](https://user-images.githubusercontent.com/1132836/185414875-0a107bef-fcc3-46c4-b5cc-181ddd4e8894.png)
![Screenshot_20220818-153524](https://user-images.githubusercontent.com/1132836/185414886-bfb330f6-c996-4edb-a96b-5d776f8f6efa.png)

I've created a test for it myself and also couldn't reproduce this errror. If I'm looking at your stacktrace, I think the commit https://github.com/TobiasBuchholz/Plugin.Firebase/commit/984f79cbe927d3128e0a464d1b1c1daa69517789 has fixed this issue already and was released with the plugin version 1.1.0.

Maybe you have some older version cached or something like this? Otherwise I've no idea how this could be possible.

**Comment by Kapusch** [comment]
Hello @TobiasBuchholz , did you test the sample app with a reference to your last released NuGet ?
Because I tried it with a direct reference to your project (not the NuGet) for debug purpose, and it's exactly as you said : the error is not reproducible...

Would it be possible that the NuGet has been released without the fix ? (e.g. Merge conflict, ...)

**Comment by TobiasBuchholz** [comment]
I've just unpacked your zip file, opened the project, restored the nuget packages and started it. The project is referencing the plugin version 1.1.2 and if you decompile the package you can see the code for the fix is contained:

<img width="1680" alt="Screenshot 2022-08-19 at 15 28 23" src="https://user-images.githubusercontent.com/1132836/185630036-c5bc8f32-eaab-4a44-9733-87c06f4aa2d3.png">

So I still believe there is no problem and you can close the issue if you think so as well.

**Comment by Kapusch** [comment]
You were right @TobiasBuchholz , I completely forgot that I had referenced a local version I made of your package, with the exact version number ... obviously this has led to mismatch the actual one I did want to target !

Indeed, here is what mentions the [documentation about package references](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#nugetdefaultsconfig-settings) : 
`For projects using the PackageReference format, NuGet uses local sources first, then sources on network shares, then HTTP sources, regardless of the order in the configuration files.`.

Hence, the solution I opted for is creating a `nuget.config` with a `packageSourceMapping` section for mapping the right package sources, whether it's nuget.org or local path.

And I was able to confirm it now downloads from the official package source :
```
Package source mapping matches found for package ID 'Plugin.Firebase' are: 'nuget.org'.
  GET https://api.nuget.org/v3-flatcontainer/plugin.firebase/index.json
  OK https://api.nuget.org/v3-flatcontainer/plugin.firebase/index.json 229ms
  GET https://api.nuget.org/v3-flatcontainer/plugin.firebase/1.1.2/plugin.firebase.1.1.2.nupkg
  OK https://api.nuget.org/v3-flatcontainer/plugin.firebase/1.1.2/plugin.firebase.1.1.2.nupkg 219ms
```

**Comment by Kapusch** [comment]
Referencing your package from the right source did fix the issue, closing ticket, thanks Tobias for your help.
