### ISSUE TITLE
Using Pages and Screens

### ISSUE THREAD

**Issue by DavidShochet** [TobiasBuchholz/Plugin.Firebase#90]
It seems like Pages and Screens is a natural place to report visiting my mobile app screens by the users. Currently, I see there information that does not seem to be very useful:

![image](https://user-images.githubusercontent.com/45371806/200391155-58dacbab-5f36-4cd1-92c4-fd9e116c1940.png)

If I change the filter criteria to have my report by Page Title and Screen Name, I get 

![image](https://user-images.githubusercontent.com/45371806/200403754-27329f51-3f49-4db2-ad80-b6b1d0ae9329.png)

I read the following:

> When you first access the report, you’ll see your data broken down according to page title and screen class. This means you’re looking at all the pages on your site, broken down by the web page title and the **developer-supplied screen name**.

I cannot figure out if/how the screen name can be supplied. Does your package support this?

**Comment by TobiasBuchholz** [comment]
A .Net MAUI app basically consists of a single activity (MainActiviy) with all the .Net MAUI framework stuff and navigation on top, but Firebase is build for native android (and iOS) apps, that are using multiple activities. These multiple activities are getting tracked automatically in native android apps, but since there is only a single MainActivity in your .Net MAUI app the automatic screen tracking only tracks this single activity. As a workaround you'll need to track the screens yourself with custom analytic events.
