### ISSUE TITLE
Map Arrays

### ISSUE THREAD

**Issue by SeriousM** [TobiasBuchholz/Plugin.Firebase#92]
A collection can be mapped to `IList<T>` and I guess it's no problem to add `T[]` to the mapping.

JavaObjectExtensions, DictionaryExtension, NSObjectExtension, ...
maybe I didn't have found all the conversion places.

We need that addition because our code requires `Array`s at certain places and `IList` isn't enough (3rd party library dependencies).

Thanks!

**Comment by TobiasBuchholz** [comment]
`IList<T>` is a more generic type than `T[]` and should suffice as only mapping since you can just convert the `IList<T>` to an array yourself, e.g. via the `.ToArray()` extension method of the `System.Linq` namespace. Hope this helps!

**Comment by TobiasBuchholz** [comment]
I think I don't understand your problem quite yet, could you please provide a concrete example at which point you are getting stuck?

**Comment by SeriousM** [comment]
I don't think it's important to state the usecase. Your library is a proxy to google firebase/firestore and thus should map between types, not educate the users what types they have to use or not. An array is a very common type and should be supported.

Here is the usecase A:
I have a target type I don't have under my control (another department, etc) which I need to use as projection type:
```cs
await documentReference.GetDocumentSnapshotAsync<TypeIHaveNotUnderMyControl>();
```

usecase B:
I have the type under my control, but must pass the instance to a service which is not under my control (another department, etc):
```cs
var snapshot = await documentReference.GetDocumentSnapshotAsync<TypeIHaveUnderMyControl>();
var data = snapshot.Data;
ServiceNotUnderMyControl.WorkOnIt(data);
```

Thanks!

**Comment by TobiasBuchholz** [comment]
Alright, I think I understand your problem now. Unfortunately implementing your suggestion is not as easy as just adding another type to a list of options. There would be some kind of another attribute necessary which specifies in the abstract object (which implements `IFirestoreObject`) that the array from firebase is supposed to be of type `T[]` instead of type `IList[]`. The conversions of abstract to native objects are taking place at [JavaObjectExtensions](https://github.com/TobiasBuchholz/Plugin.Firebase/blob/development/src/Android/Extensions/JavaObjectExtensions.cs) and [NSObjectExtension](https://github.com/TobiasBuchholz/Plugin.Firebase/blob/development/src/iOS/Extensions/NSObjectExtension.cs). Feel free to fork the project and create a pull request.

Another solution could be to follow the [adapter design pattern](https://en.wikipedia.org/wiki/Adapter_pattern) and create an object that serves as bridge between `TypeIHaveNotUnderMyControl` and `TypeIHaveUnderMyControl`.

**Comment by SeriousM** [comment]
> Unfortunately implementing your suggestion is not as easy as just adding another type to a list of options.

is it because how java/nsobject is telling what type it should be is implemented?

In c# the order of checks is important:
```cs
var obj = (object)new List<string>() { };
var obj = (object)new string[] { };

if (obj is string[] a)
{
  // its an array
}
else if (obj is IList<string> l)
{
  // its a list
}
else // other checks
{
  // ...
}
```
Even though the array implements IList<T>, a more concrete check for T[] could make the trick.

I would like to work on that myself but I lack the setup for the integration tests and I have no way to play with ios/apple.

**Comment by SeriousM** [comment]
We have changed the implementation to use `List<T>` instead.

**Comment by robertmaxted** [comment]
@SeriousM Can you elaborate on how you changed the implementation to use List<T> please? Re writing our entire code base to use IList<T> is not feasible. Any advice would be greatly appreciated.
